spring.application.name=backend

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sgli_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor (por si React usa el 3000 o 5173, evitamos choque)
server.port=8080